# Generated by Django 5.1.6 on 2025-02-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalindicador',
            name='codigo',
            field=models.CharField(db_comment='Código da indicador', default='', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='indicador',
            name='codigo',
            field=models.CharField(db_comment='Código da indicador', default='', editable=False, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='indicador',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_indicadores'),
        ),
    ]
