# Generated by Django 5.0.6 on 2024-06-29 21:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('competencia', models.CharField(db_comment='Nome da competência', max_length=100)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição da competência', null=True)),
                ('tipo_competencia', models.ForeignKey(db_comment='Identificador do tipo de competência', on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='equipes.tipocompetencia')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'db_table_comment': 'Registro de competências',
                'ordering': ['competencia'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompetencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('competencia', models.CharField(db_comment='Nome da competência', max_length=100)),
                ('descricao', models.TextField(blank=True, db_comment='Descrição da competência', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_competencia', models.ForeignKey(blank=True, db_comment='Identificador do tipo de competência', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipes.tipocompetencia')),
            ],
            options={
                'verbose_name': 'historical Competência',
                'verbose_name_plural': 'historical Competências',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
