# Generated by Django 5.0.6 on 2024-06-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0002_competencia_historicalcompetencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='competencia',
            field=models.CharField(db_comment='Nome da competência', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencia',
            name='competencia',
            field=models.CharField(db_comment='Nome da competência', db_index=True, max_length=100),
        ),
    ]
