# Generated by Django 5.0.6 on 2024-06-29 22:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0003_alter_competencia_competencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('nome', models.CharField(db_comment='Nome completo do desenvolvedor', max_length=100)),
                ('matricula', models.CharField(blank=True, db_comment='Matricula do desenvolvedor', max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_comment='E-mail do desenvolvedor', max_length=254, null=True)),
                ('ativo', models.BooleanField(db_comment='Indicador para desenvolvedor ativo', default=True)),
            ],
            options={
                'verbose_name': 'Desenvolvedor',
                'verbose_name_plural': 'Desenvolvedores',
                'db_table_comment': 'Registro dos desenvolvedores',
                'ordering': ['nome', 'matricula'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDesenvolvedor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('nome', models.CharField(db_comment='Nome completo do desenvolvedor', max_length=100)),
                ('matricula', models.CharField(blank=True, db_comment='Matricula do desenvolvedor', db_index=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, db_comment='E-mail do desenvolvedor', max_length=254, null=True)),
                ('ativo', models.BooleanField(db_comment='Indicador para desenvolvedor ativo', default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Desenvolvedor',
                'verbose_name_plural': 'historical Desenvolvedores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
