# Generated by Django 5.0.6 on 2024-06-30 00:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0005_nivelcompetencia_historicalnivelcompetencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventarioCompetencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('aquisicao_competencia', models.TextField(blank=True, db_comment='relato da aquisição da competência', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('competencia', models.ForeignKey(blank=True, db_comment='Identificador da competencia', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipes.competencia')),
                ('desenvolvedor', models.ForeignKey(blank=True, db_comment='Identificador do desenvolvedor', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipes.desenvolvedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nivel', models.ForeignKey(blank=True, db_comment='Identificador do nível da competência', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipes.nivelcompetencia')),
            ],
            options={
                'verbose_name': 'historical Inventário de Competências',
                'verbose_name_plural': 'historical Inventários de Competências',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventarioCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('aquisicao_competencia', models.TextField(blank=True, db_comment='relato da aquisição da competência', null=True)),
                ('competencia', models.ForeignKey(db_comment='Identificador da competencia', on_delete=django.db.models.deletion.PROTECT, to='equipes.competencia')),
                ('desenvolvedor', models.ForeignKey(db_comment='Identificador do desenvolvedor', on_delete=django.db.models.deletion.PROTECT, to='equipes.desenvolvedor')),
                ('nivel', models.ForeignKey(db_comment='Identificador do nível da competência', on_delete=django.db.models.deletion.PROTECT, to='equipes.nivelcompetencia')),
            ],
            options={
                'verbose_name': 'Inventário de Competências',
                'verbose_name_plural': 'Inventários de Competências',
                'db_table_comment': 'Registro do inventário de competências',
                'ordering': ['desenvolvedor', 'competencia'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventariocompetencia',
            constraint=models.UniqueConstraint(fields=('desenvolvedor', 'competencia'), name='unique_desenvolvedor_competencia'),
        ),
    ]
