# Generated by Django 5.1.4 on 2025-01-12 20:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planos', '0001_initial'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('nome', models.CharField(db_comment='Nome da origem da necessidade', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'db_table_comment': 'Tipos de origem de uma necessidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTipoOrigem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('nome', models.CharField(db_comment='Nome da origem da necessidade', db_index=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Origem',
                'verbose_name_plural': 'historical Origens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NecessidadeInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código da necessidade de informação', max_length=10, unique=True)),
                ('descricao', models.TextField(db_comment='Descrição da necessidade de informação')),
                ('areas_relacionadas', models.ManyToManyField(blank=True, db_comment='Secretarias relacionadas com a necessidade de informação', to='secretarias.secretaria')),
                ('estrategia_relacionada', models.ForeignKey(blank=True, db_comment='Princípio ou diretriz relacionada com a necessidade de informação', null=True, on_delete=django.db.models.deletion.PROTECT, to='planos.principiodiretriz')),
                ('origem', models.ForeignKey(db_comment='Tipo de origem da necessidade', on_delete=django.db.models.deletion.PROTECT, to='necessidades.tipoorigem')),
            ],
            options={
                'verbose_name': 'Necessidade de Informação',
                'verbose_name_plural': 'Necessidades de Informação',
                'db_table_comment': 'Necessidades de informação para o PDTIC',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNecessidadeInformacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código da necessidade de informação', db_index=True, max_length=10)),
                ('descricao', models.TextField(db_comment='Descrição da necessidade de informação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estrategia_relacionada', models.ForeignKey(blank=True, db_comment='Princípio ou diretriz relacionada com a necessidade de informação', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planos.principiodiretriz')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origem', models.ForeignKey(blank=True, db_comment='Tipo de origem da necessidade', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='necessidades.tipoorigem')),
            ],
            options={
                'verbose_name': 'historical Necessidade de Informação',
                'verbose_name_plural': 'historical Necessidades de Informação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
