# Generated by Django 5.1.4 on 2025-01-17 01:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessidades', '0002_tiponecessidade_historicaltiponecessidade'),
        ('planos', '0001_initial'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNecessidadeTI',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código da necessidade de TI', db_index=True, max_length=10)),
                ('descricao', models.TextField(db_comment='Descrição da necessidade de TI')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estrategia_relacionada', models.ForeignKey(blank=True, db_comment='Principio ou estratégia relacionada com à necessidade de TI', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planos.principiodiretriz')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('origem', models.ForeignKey(blank=True, db_comment='Origem da necessidade', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='necessidades.tipoorigem')),
                ('tipo_necessidade', models.ForeignKey(blank=True, db_comment='Tipo de necessidade de TI', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='necessidades.tiponecessidade')),
            ],
            options={
                'verbose_name': 'historical Necessidade de TI',
                'verbose_name_plural': 'historical Necessidades de TI',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NecessidadeTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código da necessidade de TI', max_length=10, unique=True)),
                ('descricao', models.TextField(db_comment='Descrição da necessidade de TI')),
                ('areas_relacionadas', models.ManyToManyField(db_comment='Secretarias relacionadas com a necessidade de TI', to='secretarias.secretaria')),
                ('estrategia_relacionada', models.ForeignKey(blank=True, db_comment='Principio ou estratégia relacionada com à necessidade de TI', null=True, on_delete=django.db.models.deletion.PROTECT, to='planos.principiodiretriz')),
                ('origem', models.ForeignKey(db_comment='Origem da necessidade', on_delete=django.db.models.deletion.PROTECT, to='necessidades.tipoorigem')),
                ('tipo_necessidade', models.ForeignKey(db_comment='Tipo de necessidade de TI', on_delete=django.db.models.deletion.PROTECT, to='necessidades.tiponecessidade')),
            ],
            options={
                'verbose_name': 'Necessidade de TI',
                'verbose_name_plural': 'Necessidades de TI',
                'db_table_comment': 'Inventário de Necessidades de TI para o PDTIC',
                'ordering': ['codigo'],
            },
        ),
    ]
