# Generated by Django 5.1.6 on 2025-02-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessidades', '0004_alter_necessidadeinformacao_areas_relacionadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltiponecessidade',
            name='prefixo',
            field=models.CharField(db_comment='Prefixo do tipo de necessidade', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='tiponecessidade',
            name='prefixo',
            field=models.CharField(db_comment='Prefixo do tipo de necessidade', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltiponecessidade',
            name='nome',
            field=models.CharField(db_comment='Nome do tipo de necessidade', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltipoorigem',
            name='nome',
            field=models.CharField(db_comment='Nome da origem da necessidade', max_length=100),
        ),
        migrations.AlterField(
            model_name='tiponecessidade',
            name='nome',
            field=models.CharField(db_comment='Nome do tipo de necessidade', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipoorigem',
            name='nome',
            field=models.CharField(db_comment='Nome da origem da necessidade', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tiponecessidade',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_nome_tipo_necessidade'),
        ),
        migrations.AddConstraint(
            model_name='tiponecessidade',
            constraint=models.UniqueConstraint(fields=('prefixo',), name='unique_prefixo_tipo_necessidade'),
        ),
        migrations.AddConstraint(
            model_name='tipoorigem',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_nome_origem'),
        ),
    ]
