# Generated by Django 5.1.6 on 2025-02-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessidades', '0005_historicaltiponecessidade_prefixo_and_more'),
        ('planos', '0004_fontediretriz_and_more'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnecessidadeti',
            name='codigo',
            field=models.CharField(db_comment='Código da necessidade de TI', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='necessidadeti',
            name='codigo',
            field=models.CharField(db_comment='Código da necessidade de TI', default='', editable=False, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='necessidadeti',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo_necessidade'),
        ),
    ]
