# Generated by Django 5.1.6 on 2025-02-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necessidades', '0006_alter_historicalnecessidadeti_codigo_and_more'),
        ('planos', '0004_fontediretriz_and_more'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnecessidadeinformacao',
            name='codigo',
            field=models.CharField(db_comment='Código da necessidade de informação', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='necessidadeinformacao',
            name='codigo',
            field=models.CharField(db_comment='Código da necessidade de informação', default='', editable=False, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='necessidadeinformacao',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo_necessidade_informacao'),
        ),
    ]
