# Generated by Django 4.0 on 2021-12-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsecretaria',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
