# Generated by Django 5.1.4 on 2025-01-06 01:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrincipioDiretriz',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código do princípio ou diretriz levantada', max_length=10)),
                ('principio_diretriz', models.CharField(db_comment='Descrição do princípio ou diretriz que precisa ser observada no PDTIC', max_length=250)),
                ('origem', models.CharField(db_comment='Nome do documento de origem do princípio ou diretriz', max_length=100)),
                ('criterio_priorizacao', models.BooleanField(db_comment='Indica se o princípio ou diretriz é critério de priorização das necessidades', default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Princípio ou Diretriz',
                'verbose_name_plural': 'historical Princípios ou Diretrizes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PrincipioDiretriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código do princípio ou diretriz levantada', max_length=10)),
                ('principio_diretriz', models.CharField(db_comment='Descrição do princípio ou diretriz que precisa ser observada no PDTIC', max_length=250)),
                ('origem', models.CharField(db_comment='Nome do documento de origem do princípio ou diretriz', max_length=100)),
                ('criterio_priorizacao', models.BooleanField(db_comment='Indica se o princípio ou diretriz é critério de priorização das necessidades', default=False)),
            ],
            options={
                'verbose_name': 'Princípio ou Diretriz',
                'verbose_name_plural': 'Princípios ou Diretrizes',
                'db_table_comment': 'Lista de princípios ou diretrizes que devem ser observadas na produção do PDTIC',
                'ordering': ['codigo', 'origem'],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='unique_codigo_principio_diretriz')],
            },
        ),
    ]
