# Generated by Django 5.1.6 on 2025-02-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprincipiodiretriz',
            name='codigo',
            field=models.CharField(db_comment='Código do princípio ou diretriz levantada', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='principiodiretriz',
            name='codigo',
            field=models.CharField(db_comment='Código do princípio ou diretriz levantada', default='', editable=False, max_length=10),
        ),
    ]
