# Generated by Django 5.1.6 on 2025-02-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_alter_historicalprincipiodiretriz_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprincipiodiretriz',
            name='principio_diretriz',
            field=models.TextField(db_comment='Descrição do princípio ou diretriz que precisa ser observada no PDTIC'),
        ),
        migrations.AlterField(
            model_name='principiodiretriz',
            name='principio_diretriz',
            field=models.TextField(db_comment='Descrição do princípio ou diretriz que precisa ser observada no PDTIC'),
        ),
    ]
