# Generated by Django 5.1.6 on 2025-02-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_alter_historicalprincipiodiretriz_principio_diretriz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDiretriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_comment='Nome da fonte de Diretrizes', max_length=100)),
            ],
            options={
                'verbose_name': 'Fonte de Diretrizes',
                'verbose_name_plural': 'Fontes de Diretrizes',
                'db_table_comment': 'Lista de fontes de diretrizes(Planos Municipais, Leis, recomendação do TCESP, entre outros)',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('nome',), name='unique_nome_fonte_diretriz')],
            },
        ),
        migrations.AlterField(
            model_name='historicalprincipiodiretriz',
            name='origem',
            field=models.ForeignKey(blank=True, db_comment='Nome do documento de origem do princípio ou diretriz', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='planos.fontediretriz'),
        ),
        migrations.AlterField(
            model_name='principiodiretriz',
            name='origem',
            field=models.ForeignKey(db_comment='Nome do documento de origem do princípio ou diretriz', on_delete=django.db.models.deletion.PROTECT, to='planos.fontediretriz'),
        ),
    ]
