# Generated by Django 5.1.4 on 2025-01-19 19:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código da ação', max_length=10, unique=True)),
                ('nome', models.TextField(db_comment='Nome da ação', unique=True)),
                ('data_inicio_estimada', models.DateField(db_comment='Data de início estimada para a ação')),
                ('data_conclusao_estimada', models.DateField(db_comment='Data de conslusão estimada para a ação')),
                ('areas_responsaveis', models.ManyToManyField(db_comment='Áreas responsáveis pela ação', related_name='acoes_areas', to='secretarias.secretaria')),
                ('metas', models.ManyToManyField(db_comment='Metas relacionadas com uma ação', related_name='acoes_metas', to='metas.meta')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'db_table_comment': 'Ações relacionadas a um ou mais metas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAcao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('codigo', models.CharField(db_comment='Código da ação', db_index=True, max_length=10)),
                ('nome', models.TextField(db_comment='Nome da ação', db_index=True)),
                ('data_inicio_estimada', models.DateField(db_comment='Data de início estimada para a ação')),
                ('data_conclusao_estimada', models.DateField(db_comment='Data de conslusão estimada para a ação')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ação',
                'verbose_name_plural': 'historical Ações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
