# Generated by Django 5.1.4 on 2025-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
        ('metas', '0003_acao_competencias_acao_quantidade_pessoas_and_more'),
        ('necessidades', '0003_historicalnecessidadeti_necessidadeti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeta',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='indicador',
        ),
        migrations.AddField(
            model_name='meta',
            name='indicadores',
            field=models.ManyToManyField(related_name='metas_indicador', to='indicadores.indicador'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='necessidades',
            field=models.ManyToManyField(related_name='metas_necessidade', to='necessidades.necessidadeti'),
        ),
    ]
