# Generated by Django 5.1.4 on 2025-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_remove_historicalmeta_indicador_and_more'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='areas_responsaveis',
            field=models.ManyToManyField(related_name='acoes_areas', to='secretarias.secretaria'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='metas',
            field=models.ManyToManyField(related_name='acoes_metas', to='metas.meta'),
        ),
    ]
