# Generated by Django 5.1.6 on 2025-02-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
        ('metas', '0005_alter_acao_areas_responsaveis_alter_acao_metas'),
        ('necessidades', '0007_alter_historicalnecessidadeinformacao_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeta',
            name='codigo',
            field=models.CharField(db_comment='Código da meta', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalmeta',
            name='nome',
            field=models.TextField(db_comment='Nome da meta'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='codigo',
            field=models.CharField(db_comment='Código da meta', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='meta',
            name='nome',
            field=models.TextField(db_comment='Nome da meta'),
        ),
        migrations.AddConstraint(
            model_name='meta',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo_meta'),
        ),
        migrations.AddConstraint(
            model_name='meta',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_nome_meta'),
        ),
    ]
