# Generated by Django 5.1.6 on 2025-02-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0006_historicalinventariocompetencia_and_more'),
        ('metas', '0006_alter_historicalmeta_codigo_and_more'),
        ('secretarias', '0004_alter_historicalsecretaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='codigo',
            field=models.CharField(db_comment='Código da ação', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='acao',
            name='nome',
            field=models.TextField(db_comment='Nome da ação'),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='codigo',
            field=models.CharField(db_comment='Código da ação', default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalacao',
            name='nome',
            field=models.TextField(db_comment='Nome da ação'),
        ),
        migrations.AddConstraint(
            model_name='acao',
            constraint=models.UniqueConstraint(fields=('codigo',), name='unique_codigo_acao'),
        ),
        migrations.AddConstraint(
            model_name='acao',
            constraint=models.UniqueConstraint(fields=('nome',), name='unique_nome_acao'),
        ),
    ]
