# Generated by Django 5.1.4 on 2025-01-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltipoambiente',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tipo de Ambiente', 'verbose_name_plural': 'historical Tipos de Ambiente'},
        ),
        migrations.AlterModelOptions(
            name='tipoambiente',
            options={'verbose_name': 'Tipo de Ambiente', 'verbose_name_plural': 'Tipos de Ambiente'},
        ),
        migrations.AlterModelTableComment(
            name='tipoambiente',
            table_comment='Tipos de ambiente na análise SWOT',
        ),
    ]
