# Generated by Django 5.1.4 on 2025-01-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0003_historicaltipoavaliacao_tipoavaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoambiente',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Ambiente', 'verbose_name_plural': 'Tipos de Ambiente'},
        ),
    ]
