# Generated by Django 5.1.4 on 2025-01-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0004_alter_tipoambiente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoavaliacao',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Avaliação', 'verbose_name_plural': 'Tipos de Avaliação'},
        ),
    ]
