# Generated by Django 5.1.4 on 2025-01-12 03:04

import django.db.models.deletion
import simple_history.models
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0005_alter_tipoavaliacao_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSwot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data_inclusao', models.DateField(blank=True, editable=False, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(blank=True, editable=False, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(blank=True, editable=False, verbose_name='Hora de Alteração')),
                ('descricao', models.CharField(db_comment='Descrição do ponto analisado', db_index=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_ambiente', models.ForeignKey(blank=True, db_comment='Tipo de ambiente', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='swot.tipoambiente')),
                ('tipo_avaliacao', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tipo_ambiente', chained_model_field='tipo_avaliacao', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', show_all=True, to='swot.tipoavaliacao')),
            ],
            options={
                'verbose_name': 'historical Swot',
                'verbose_name_plural': 'historical Swots',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Swot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True, verbose_name='Data de Inclusão')),
                ('hora_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Hora de Inclusão')),
                ('data_alteracao', models.DateField(auto_now=True, verbose_name='Data de Alteração')),
                ('hora_alteracao', models.DateTimeField(auto_now=True, verbose_name='Hora de Alteração')),
                ('descricao', models.CharField(db_comment='Descrição do ponto analisado', max_length=100, unique=True)),
                ('tipo_ambiente', models.ForeignKey(db_comment='Tipo de ambiente', on_delete=django.db.models.deletion.PROTECT, to='swot.tipoambiente')),
                ('tipo_avaliacao', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tipo_ambiente', chained_model_field='tipo_avaliacao', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='swot.tipoavaliacao')),
            ],
            options={
                'verbose_name': 'Swot',
                'verbose_name_plural': 'Swots',
                'ordering': ['descricao'],
            },
        ),
    ]
