# Generated by Django 5.1.4 on 2025-01-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot', '0008_alter_historicalswot_tipo_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalswot',
            name='descricao',
            field=models.TextField(db_comment='Descrição do ponto analisado'),
        ),
        migrations.AlterField(
            model_name='swot',
            name='descricao',
            field=models.TextField(db_comment='Descrição do ponto analisado'),
        ),
    ]
